# Lecture Schedule

Select a lecture from the menu to see details about topics, readings, and assignments. Additional notes and links to course materials are available through the [course website](https://slu-soc5050.github.io), which has dedicated pages for each lecture. Links to these pages are included on each lecture's reading list entry. 

The primary readings will be referred to with an abbreviation each time they appear in the reading list:

```{r, echo=FALSE}
readings <- data.frame(
  Abbreviation = c("Brewer", "Tutorial", "R4DS"),
  Citation = c("Brewer, Cynthia. 2015. *Designing Better Maps: A Guide for GIS users*. Redlands, CA: ESRI Press.", 
               "Gorr, Wilpen and Kristen Kurland. 2017. *GIS Tutorial 1 for ArcGIS Pro.* Redlands, CA: ESRI Press.",
               "Wickham, Hadley and Garrett Grolemund. 2016. *R for data science: import, tidy, transform, visualize, and model data*. Sebastopol, CA: O'Reilly Media, Inc."),
  stringsAsFactors = FALSE
)

knitr::kable(
  readings, booktabs = TRUE,
  caption = "SOC 4650 and 5650 Primary Readings"
)
```

## Course Preview {-}

<div class="button"><a href="https://slu-soc5650.github.io/docs/course-preview/" target="_blank">View on Course Website</a></div>

<br>
<br>

### Topics {-}

* **GIScience** - Open Data, GISc, and Public Policy
- **Analysis Development** - Opinionated Analysis Development and Plain Text Data Science

### Videos {-}

#### Required {-}

* Coral, Lilian. 2016. "City of Los Angeles GeoHub." Presented at the ESRI User Conference, San Diego, CA. (<a href="https://slu-soc5050.github.io/course-preview/#open-data-and-gis-in-los-angeles" target="_blank">Link</a>)
* Parker, Hilary. 2017. "Opinionated analysis development." Presented at rstudio::conf, Orlando, FL. (<a href="https://slu-soc5050.github.io/course-preview/#analysis-development" target="_blank">Link</a>)

### Readings {-}

#### Required {-}

* Healy, Kieran. 2018. "Introduction." In *The plain person's guide to plain text*. (<a href="http://plain-text.co/index.html" target="_blank">Link</a>) 

#### *Optional* {-}

* Parker Hilary. 2017. "Opinionated analysis development." *PeerJ Preprints* 5:e3210v1. (<a href="https://doi.org/10.7287/peerj.preprints.3210v1" target="_blank">Link</a>) 
* Thieme, Nick. 2018. "R generation." *Significance* 15(4):14-19. (<a href="https://rss.onlinelibrary.wiley.com/doi/10.1111/j.1740-9713.2018.01169.x" target="_blank">Link</a>) 

### Assignments {-}

#### Due Before *First* Lecture {-}

* <a href="https://slu-soc5650.github.io/docs/course-preview/#lecture-01-entry-ticket" target="_blank">eTicket-01</a>

## Lecture-01 - Course Introduction {-}

<div class="button"><a href="https://slu-soc5650.github.io/docs/lecture-01/" target="_blank">View on Course Website</a></div>

<br>
<br>

### Topics {-}

* **GIScience** - What are GIS and GISc?
* **Data Management** - Intro to `R` and RStudio
* **Data Visualization** - What Makes a Good Map, `leaflet`
* **Analysis Development** - Workflows

### Readings {-}

#### Required {-}

* Goodchild, Michael. 2010. "Twenty years of progress: GIScience in 2010." *Journal of Spatial Information Science* 1(1):3-20. (<a href="http://eres.slu.edu/eres/coursepage.aspx?cid=4444" target="_blank">Electronic Reserves</a>)
* Logan, John. 2010. "Making a place for space: Spatial thinking in social science." *Annual Review of Sociology* 38:507-524. (<a href="http://eres.slu.edu/eres/coursepage.aspx?cid=4444" target="_blank">Electronic Reserves</a>)
* R4DS:
    - *Print* - Preface ***or***
    - *Web* - Chapter 1 (<a href="http://r4ds.had.co.nz" target="_blank">Link</a>)

#### *Optional* {-}

* Wilson, Greg, Jennifer Bryan, Karen Cranston, Justin Kitzes, Lex Nederbragt, and Tracy Teal. 2017. "Good enough practices in scientific computing." *PLoS Computational Niology* 13(6):e1005510. (<a href="http://eres.slu.edu/eres/coursepage.aspx?cid=4444" target="_blank">Electronic Reserves</a>)

### Assignments {-}

#### Due *Before* Lecture {-}

* eTicket-01

## Lecture-02 - ArcGIS Pro Overview {-}

<div class="button"><a href="https://slu-soc5650.github.io/docs/lecture-02/" target="_blank">View on Course Website</a></div>

<br>
<br>

### Topics {-}

* **Data Visualization** - The ArcGIS Platform
* **Analysis Development** - ArcGIS Projects

### Readings {-}

* Tutorial: Chapter 1 (<a href="https://esripress.esri.com/storage/esripress/images/340/gistoneprochapone.pdf" target="_blank">Link</a>)

### Assignments {-}

#### Due *Before* Lecture {-}

* eTicket-02

#### Due Before *Next* Lecture {-}

* eTicket-03
* Lab-01 - Introduction to ArcGIS Pro 

## Lecture-03 - Cartography 101 {-}

<div class="button"><a href="https://slu-soc5650.github.io/docs/lecture-03/" target="_blank">View on Course Website</a></div>

<br>
<br>

### Topics {-}

* **GIScience** - Methodological Challenges for Representing Geography
* **Data Visualization** - Basics of Cartography

### Readings {-}

#### Required {-}

* Brewer: Chapters 1-2, 7-8
* Tutorial: Chapter 2, *part*, pp. 45-62

* Tufte, Edward. 1990. "Color and Information." Pp. 81-95 in *Envisioning Information*. Cheshire, CT: Graphics Press. (<a href="http://eres.slu.edu/eres/coursepage.aspx?cid=4444" target="_blank">Electronic Reserves</a>)
* Tufte, Edward. 2001 "Data Maps." Pp. 16-27 in *The Visual Display of Quantitative Information*. Cheshire, CT: Graphics Press. (<a href="http://eres.slu.edu/eres/coursepage.aspx?cid=4444" target="_blank">Electronic Reserves</a>)


#### Optional {-}

* Borland, David and Russell M. Taylor II. 2007. "Rainbow color map (still) considered harmful." *IEEE computer graphics and applications* 27(2). (<a href="https://ieeexplore.ieee.org/abstract/document/4118486" target="_blank">Link</a>)
* Brewer, Cynthia A., Alan M. MacEachren, Linda W. Pickle, and Douglas Herrmann. 1997. "Mapping mortality: Evaluating color schemes for choropleth maps." *Annals of the Association of American Geographers* 87(3):411-438. (<a href="https://onlinelibrary.wiley.com/doi/abs/10.1111/1467-8306.00061" target="_blank">Link</a>)
* Olson, Judy M., and Cynthia A. Brewer. 1997. "An evaluation of color selections to accommodate map users with color‐vision impairments." *Annals of the Association of American Geographers* 87(1):103-134. (<a href="https://onlinelibrary.wiley.com/doi/abs/10.1111/0004-5608.00043" target="_blank">Link</a>)

### Assignments {-}

#### Due *Before* Lecture {-}

* *From Lecture-02* - Lab-01 - Introduction to ArcGIS Pro 
* eTicket-03

#### Due Before *Next* Lecture {-}

* Lab-02 - Cartographic Design
* eTicket-04
* *From Final Project* - WP-01 - topic selection

## Lecture-04 - Map Production in ArcGIS Pro {-}

<div class="button"><a href="https://slu-soc5650.github.io/docs/lecture-04/" target="_blank">View on Course Website</a></div>

<br>
<br>

### Topics {-}

* **Data Visualization** - 
    * Typography
    * Mapping with ArcGIS Pro

### Readings {-}

* Brewer: Chapters 3, 5, and 6
* Tufte, Edward. 2001 ``Chartjunk.'' Pp. 1007-121 in *The Visual Display of Quantitative Information*. Cheshire, CT: Graphics Press. (<a href="http://eres.slu.edu/eres/coursepage.aspx?cid=4444" target="_blank">Electronic Reserves</a>)
* Tutorial: 
    * Chapter 2, *part*, pp. 65-79
    * Chapter 3, *part*, pp. 83-100

### Assignments {-}

#### Due *Before* Lecture {-}

* *From Lecture-03* - Lab-02 - Cartographic Design
* *From Final Project* - WP-01 - Topic Selection
* eTicket-04

#### Due Before *Next* Lecture {-}

* Lab-03 - Map Production in ArcGIS Pro
* eTicket-05

#### Due in *Two* Lectures {-}

* PS-01 - Map Production in ArcGIS Pro

## Lecture-05 - Map Production in `R` {-}

<div class="button"><a href="https://slu-soc5650.github.io/docs/lecture-05/" target="_blank">View on Course Website</a></div>

<br>
<br>

### Topics {-}

* **Data Visualization** - Interactive Mapping with `R`
* **Analysis Development** - R Projects, Notebooks, and R Markdown

### Readings {-}

* R4DS, Analysis Development:
    - *Print* - Preface, Part I Intro (pp. 1-2), Chapters 2, 4, and 6 ***or***
    - *Web* - Chapters 1, 2, 4, 6, and 8 (<a href="http://r4ds.had.co.nz" target="_blank">Link</a>)
* R4DS, Data Visualization:
    - *Print* - Chapter 1, *part*, pp. 3-13 **or**
    - *Web* - Chapter 3, *part*, Sections 3.1-3.4 (<a href="http://r4ds.had.co.nz" target="_blank">Link</a>)

### Assignments {-}

#### Due *Before* Lecture {-}

* *From Lecture-04* - Lab-03 - Map Production in ArcGIS Pro
* eTicket-05

#### Due Before *Next* Lecture {-}

* *From Lecture-04* - PS-01 - Map Production in ArcGIS Pro
* Lab-04 - Map Production in `R`
* eTicket-06

#### Due in *Two* Lectures {-}

* PS-02 - Map Production in `R`

## Lecture-06 - More Map Production in `R` {-}

<div class="button"><a href="https://slu-soc5650.github.io/docs/lecture-06/" target="_blank">View on Course Website</a></div>

<br>
<br>

### Topics {-}

* **Data Visualization** - Static Mapping in `R`

### Readings {-}

#### Required {-}

* Lovelace, Robin, Jakub Nowosad, and Jannes Muenchow. 2019. *Geocomputation with R.* New York, NY: CRC Press. Chapter 8, *part*, Sections 8.1-8.2 (<a href="https://geocompr.robinlovelace.net/adv-map.html" target="_blank">Link</a>)

### Assignments {-}

#### Due *Before* Lecture {-}

* *From Lecture-04* - PS-01 - Map Production in ArcGIS Pro
* *From Lecture-05* - Lab-04 - Interactive Map Production in `R`
* eTicket-06

#### Due Before *Next* Lecture {-}

* Lab-05 - Static Map Production in `R`
* eTicket-07

#### Due in *Two* Lectures {-}

* *From Lectures 04 & 05* - PS-02 - Map Production in `R`

## Lecture-07 - Data Cleaning {-}

<div class="button"><a href="https://slu-soc5650.github.io/docs/lecture-07/" target="_blank">View on Course Website</a></div>

<br>
<br>

### Topics {-}

* **Data Management** - Preparing Data for Mapping

### Readings {-}

* R4DS:
    - *Print* - Chapter 3, *part*, pp. 43-58 **or**
    - *Web* - Chapter 5, *part*, Sections 5.1-5.5 (<a href="http://r4ds.had.co.nz" target="_blank">Link</a>)

### Assignments {-}

#### Due *Before* Lecture {-}

* *From Lecture-06* - Lab-05 - Static Map Production in `R`
* eTicket-07

#### Due Before *Next* Lecture {-}

* *From Final Project* - WP-02
    * *SOC 5650 only* - Annotated Bibliography
* *From Lectures 04 & 05* - PS-02 - Map Production in `R`
* Lab-06 - Data Cleaning
* eTicket-08

#### Due in *Two* Lectures {-}

* PS-03 - Data Cleaning

## Lecture-08 - Table Joins; Data Storage {-}

<div class="button"><a href="https://slu-soc5650.github.io/docs/lecture-08/" target="_blank">View on Course Website</a></div>

<br>
<br>

### Topics {-}

* **Data Management** - 
    * Combining Multiple Tables
    * Exporting Data from ArcGIS Pro and `R`
    * Geodatabases

### Readings {-}

* R4DS:
    - *Print* - Chapter 10, *part*, pp. 171-1782 **or**
    - *Web* - Chapter 13, *part*, Sections 13.1-13.4 (<a href="http://r4ds.had.co.nz" target="_blank">Link</a>)
* Tutorial: Chapter 4, *part*, Tutorials 4-1 and 4-4

### Assignments {-}

#### Due *Before* Lecture {-}

* *From Lecture-07* - Lab-06 - Data Cleaning
* *From Final Project* - WP-02
    * *SOC 5650 only* - Annotated Bibliography
* eTicket-08

#### Due Before *Next* Lecture {-}

* *From Lecture-07* - PS-03 - Data Cleaning
* Lab-07 - Joining and Storing Data

## Lecture-09 - Accessing Census Data via APIs {-}

<div class="button"><a href="https://slu-soc5650.github.io/docs/lecture-09/" target="_blank">View on Course Website</a></div>

<br>
<br>

### Topics {-}

* **Data Management** - Georeferenced Demographic Data

### Videos {-}

1. Video a - American Fact Finder (<a href="https://www.youtube.com/watch?v=si4-3WTgOsc" target="_blank">Link</a>)
2. Video b - Accessing Census Data in `R` (<a href="https://www.youtube.com/watch?v=PxXoIV2YzwU" target="_blank">Link</a>)
3. Video c - Accessing Spatial Data in `R` (<a href="https://www.youtube.com/watch?v=GeKLvsMgavw" target="_blank">Link</a>)

*Note*: These videos are labeled as "Lecture-08" on YouTube, which was the lecture they were given under during Spring 2018. 

### Assignments {-}

#### Due *Before* Lecture {-}

* *From Lecture-07* - PS-03 - Data Cleaning
* *From Lecture-08* - Lab-07 - Joining and Storing Data

#### Due Before *Next* Lecture {-}

* Lab-08 - Georeferenced Demographic Data
* eTicket-09

## Lecture-10 - Managing Projections {-}

<div class="button"><a href="https://slu-soc5650.github.io/docs/lecture-10/" target="_blank">View on Course Website</a></div>

<br>
<br>

### Topics {-}

* **GIScience** - Geographic and Projected Coordinate Systems
* **Data Management** - 
     * Transforming Coordinate Systems 
     * Working with Dates and Strings

### Readings {-}

1. Maher, Margaret. 2013. "Defining Projections and Their Parameters; Adding x,y Data; Analyzing the Shape of Buffers." Pp. 167-182 in *Lining up data in ArcGIS: A Guide to Map Projections.* Redlands, CA: ESRI Press. (<a href="http://eres.slu.edu/eres/coursepage.aspx?cid=4444" target="_blank">Electronic Reserves</a>)
2. Maher, Margaret. 2013. "Identifying the Projected Coordinate System." Pp. 35-55 in *Lining up data in ArcGIS: A Guide to Map Projections.* Redlands, CA: ESRI Press. (<a href="http://eres.slu.edu/eres/coursepage.aspx?cid=4444" target="_blank">Electronic Reserves</a>)
3. Tutorial: Chapter 5, *part*, pp. 163-180
4. R4DS:
    - *Print* - Chapters 11 and 13 **or**
    - *Web* - Chapters 14 and 16 (<a href="http://r4ds.had.co.nz" target="_blank">Link</a>)


*Note:* Read these readings in the order specified here.

### Assignments {-}

#### Due *Before* Lecture {-}

* *From Lecture-09* - Lab-08 - Georeferenced Demographic Data
* eTicket-09

#### Due Before *Next* Lecture {-}

* *From Final Project* - WP-03
* Lab-09 - Managing Projections

#### Due in *Two* Lectures {-}

* PS-04 - Managing Projections

## Lecture-11 - Select and Aggregate Features {-}

<div class="button"><a href="https://slu-soc5650.github.io/docs/lecture-11/" target="_blank">View on Course Website</a></div>

<br>
<br>

### Topics {-}

* **GIScience** - Centroids
* **Data Management** - 
    * Select by Location
    * Spatial Joins

### Readings {-}

* R4DS:
    - *Print* - Chapter 3, *part*, pp. 59-76 **or**
    - *Web* - Chapter 5, *part*, Section 5.6 (<a href="http://r4ds.had.co.nz" target="_blank">Link</a>)
* Tutorial: Chapter 4, *part*, Tutorial 4-5

### Assignments {-}

#### Due *Before* Lecture {-}

* *From Final Project* - WP-03
* *From Lecture-10* - Lab-09 - Managing Projections

#### Due Before *Next* Lecture {-}

* *From Lecture-10* - PS-04 - Managing Projections
* Lab-10 - Select and Aggregate Features
* eTicket-10

#### Due in *Two* Lectures {-}

* PS-05 - Select and Aggregate Features

## Lecture-12 - Clip and Dissolve Features {-}

<div class="button"><a href="https://slu-soc5650.github.io/docs/lecture-12/" target="_blank">View on Course Website</a></div>

<br>
<br>

### Topics {-}

* **Data Management** - 
    * Clipping Features
    * Disolving Features
* **Data Visualization** - Customizing Symbols

### Readings {-}

* Brewer: Chapter 9 
* Tutorial: Chapter 6, *part*, Tutorials 6-1 and 6-2

### Assignments {-}

#### Due *Before* Lecture {-}

* *From Lecture-10* - PS-04 - Managing Projections
* *From Lecture-11* - Lab-10 - Select and Aggregate Features
* eTicket-10

#### Due Before *Next* Lecture {-}

* *From Lecture-11* - PS-05 - Select and Aggregate Features
* *From Final Project* - WP-04 - Draft Materials
* Lab-11 - Clip and Dissolve Features

## Lecture-13 - Intersect, Union, and Merge Features {-}

<div class="button"><a href="https://slu-soc5650.github.io/docs/lecture-13/" target="_blank">View on Course Website</a></div>

<br>
<br>

### Topics {-}

* **Data Management** - 
    * Intersect Features
    * Union Features
    * Merge Features

### Readings {-}

* Tutorial: Chapter 6, *part*, Tutorials 6-3 through 6-6

### Assignments {-}

#### Due *Before* Lecture {-}

* *From Lecture-11* - PS-05 - Select and Aggregate Features
* *From Lecture-12* - Lab-11 - Clip and Dissolve Features
* *From Final Project* - WP-04 - Draft Materials

#### Due Before *Next* Lecture {-}

* *From Final Project* - WP-05 - Peer Reviews
* Lab-12 - Intersect, Union, and Merge Features

#### Due in *Two* Lectures {-}

* PS-06 - Geoprocessing Data

## Lecture-14 - Digitizing Data {-}

<div class="button"><a href="https://slu-soc5650.github.io/docs/lecture-14/" target="_blank">View on Course Website</a></div>

<br>
<br>

### Topics {-}

* **GIScience** - Raster Data
* **Data Management** - Creating Vector Data

### Readings {-}

* Tutorial: Chapter 7
* Tutorial: Chapter 10, *part*, Tutorial 10-1

### Assignments {-}

#### Due *Before* Lecture {-}

* *From Lecture-13* - Lab-12 - Intersect, Union, and Merge Features
* *From Final Project* - WP-05 - Peer Reviews

#### Due Before *Next* Lecture {-}

* *From Lectures 12 and 13* - PS-06 - Geoprocessing Data
* Lab-13 - Digitizing Data
* eTicket-11

## Lecture-15 - Geocoding Data {-}

<div class="button"><a href="https://slu-soc5650.github.io/docs/lecture-15/" target="_blank">View on Course Website</a></div>

<br>
<br>

### Topics {-}

* **GIScience** - Geolocating Point Data
* **Data Management** - Geocoding Data in `R` and `ArcGIS`

### Readings {-}

* Tutorial: Chapter 8

### Assignments {-}

#### Due *Before* Lecture {-}

* *From Lectures 12 and 13* - PS-06 - Geoprocessing Data
* *From Lecture-14* - Lab-13 - Digitizing Data
* eTicket-11

#### Due Before *Next* Lecture {-}

* *From Final Project* - WP-06
* Lab-14 - Geocoding Data

## Lecture-16 - Basic Spatial Analyses {-}

<div class="button"><a href="https://slu-soc5650.github.io/docs/lecture-16/" target="_blank">View on Course Website</a></div>

<br>
<br>

### Topics {-}

* **GIScience** - An Introduction to Spatial Analyses

### Readings {-}

* Tutorial: 
    * Chapter 9, *part*, Tutorial 9-1
    * Chapter 10, *part*, Tutorial 10-2

### Assignments {-}

#### Due *Before* Lecture {-}

* *From Lecture-15* - Lab-14 - Geocoding Data
* *From Final Project* - WP-06

#### Due Before *Next* Lecture {-}

* Lab-15 - Spatial Analyses

## Lecture-17 - Combining `R` and ArcGIS Pro with Python {-}

<div class="button"><a href="https://slu-soc5650.github.io/docs/lecture-17/" target="_blank">View on Course Website</a></div>

<br>
<br>

### Topics {-}

* **GIScience** - Programming for ArcGIS 

### Assignments {-}

#### Due *Before* Lecture {-}

* *From Lecture-16* - Lab-15 - Spatial Analyses

#### Due Before *Next* Class Meeting {-}

* *From Final Project* - Final Code, Docs, and Presentation
    * *SOC 5650 only* - Final Paper

## Final Presentations {-}

### Topics {-}

* **Research Synthesis** - Final Presentations

### Assignments Due Before Presentations {-}

* *From Final Project* - Final Code, Docs, and Presentation
    * *SOC 5650 only* - Final Paper
