# (PART) Reading List {-}

# Course Schedule

The following is a high-level schedule that details the general topic covered by each lecture.

```{r, echo=FALSE}
schedule <- data.frame(
  Lecture = c("", "", "01", "02", "03", "04", "05", "06", "", "07", "08", "09", 
              "10", "", "11", "12", "13", "14", "15", "", "16", "17", ""),
  Date = c("",
           "prior to January 14^th^", 
           "January 14^th^", 
           "January 21^st^", 
           "January 28^th^",  
           "February 4^th^", 
           "February 11^th^",
           "February 18^th^",
           "",
           "February 25^th^", 
           "March 4^th^", 
           "March 11^th^", 
           "March 18^th^", 
           "", 
           "March 25^th^", 
           "April 1^st^", 
           "April 8^th^", 
           "April 15^th^", 
           "April 22^nd^", 
           "",
           "April 29^th^", 
           "May 6^th^",
           "May 13^th^"),
  Topic = c("**Unit 1: Visualize**",
            "Course Preview", 
            "Course Introduction", 
            "ArcGIS Pro Overview", 
            "Cartography 101", 
            "Map Production in ArcGIS Pro", 
            "Map Production in `R`", 
            "Communicating with Maps", 
            "**Unit 2: Tidy**",
            "Data Cleaning", 
            "Table Joins; Data Storage", 
            "Accessing Census Data via APIs", 
            "Managing Projections", 
            "**Unit 3: Process**", 
            "Select and Aggregate Features", 
            "Clip and Dissolve Features", 
            "Intersect, Union, and Merge Features", 
            "Digitizing Data", 
            "Geocoding Data", 
            "**Unit 4: Analyze**",
            "Basic Spatial Analyses", 
            "Combining `R` and ArcGIS Pro with Python", 
            "Final Presentations"),
  stringsAsFactors = FALSE
)

knitr::kable(
  schedule, booktabs = TRUE,
  caption = "SOC 4615 and 5650 Course Overview"
)
```

## Planned Online Lectures

This semester, we have two classes that fall on official university holidays: Martin Luther King, Jr. Day (Lecture-02, **January 21^st^**) and Spring Break (Lecture-09, **March 11^th^**). These weeks will have materials assigned for them, which will include lectures posted on YouTube. These lectures will be shorter than typical in-class lectures. Students should view these lectures during that week and complete the associated readings and lab exercises. Videos will be embedded in the lecture pages on the [**course website**](https://slu-soc5650.github.io/).

## Class Progression

Each lecture will be broken down roughly the same way. Students are expected to arrive having already completed the previous week's work as well as the assigned readings and lecture prep. Class will begin with any relevant "front matter" including follow-up from the previous weeks and relevant announcements. Around 6:00pm, we will take a short break. Most classes will end with time dedicated to working through the lab exercise. After class, students are expected to finish the lab and, if necessary, the assigned problem set as well.

## Scheduling Notes

The lecture schedule may change as it depends on the progress of the class. However, you must keep up with the reading assignments. In the event of a cancellation due to weather or another disruption, I may alter the lecture schedule.

Since this course only meets once per week, cancellations are particularly disruptive. I will make every effort to schedule make-up classes at a time that works for at least a portion of the class. These class sessions will be recorded and made immediately available using YouTube for students who are unable to attend the make-up class. All students will be responsible for either attending the make-up class or watching the lecture as well as completing all readings, lab assignments, and problem sets for make-up classes.
